'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("MMProject.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property bmpBLANKSPACE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpBLANKSPACE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpCIRCLEMASK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpCIRCLEMASK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpCLOSEAPPDOWN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpCLOSEAPPDOWN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpCLOSEAPPOVER() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpCLOSEAPPOVER", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpCLOSEAPPUP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpCLOSEAPPUP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpCLOSEMASK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpCLOSEMASK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpCOLON() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpCOLON", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpENDLINE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpENDLINE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpENDLINEMASK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpENDLINEMASK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpFORWARDDOWN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpFORWARDDOWN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpFORWARDOVER() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpFORWARDOVER", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpFORWARDUP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpFORWARDUP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpMINIMIZEDDOWN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpMINIMIZEDDOWN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpMINIMIZEDMASK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpMINIMIZEDMASK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpMINIMIZEDOVER() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpMINIMIZEDOVER", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpMINIMIZEDUP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpMINIMIZEDUP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpNEGATIVE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpNEGATIVE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpNUM0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpNUM0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpNUM1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpNUM1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpNUM2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpNUM2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpNUM3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpNUM3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpNUM4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpNUM4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpNUM5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpNUM5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpNUM6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpNUM6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpNUM7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpNUM7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpNUM8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpNUM8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpNUM9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpNUM9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpOPENDOWN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpOPENDOWN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpOPENOVER() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpOPENOVER", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpOPENUP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpOPENUP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpPAUSEDOWN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpPAUSEDOWN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpPAUSEOVER() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpPAUSEOVER", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpPAUSEUP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpPAUSEUP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpPLAYDOWN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpPLAYDOWN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpPLAYOVER() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpPLAYOVER", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpPLAYUP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpPLAYUP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpREWINDDOWN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpREWINDDOWN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpREWINDOVER() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpREWINDOVER", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpREWINDUP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpREWINDUP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpSTARTLINE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpSTARTLINE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpSTARTLINEMASK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpSTARTLINEMASK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpSTOPDOWN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpSTOPDOWN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpSTOPOVER() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpSTOPOVER", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpSTOPUP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpSTOPUP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpTRACKPOSDOWN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpTRACKPOSDOWN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpTRACKPOSMASK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpTRACKPOSMASK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpTRACKPOSOVER() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpTRACKPOSOVER", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpTRACKPOSUP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpTRACKPOSUP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpVOLUMEHANDLE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpVOLUMEHANDLE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
